# nixpacks.toml - Manual de Instrucciones para Railway (Versión Corregida y Explícita)

# Fase 1: Configurar el sistema operativo del servidor
[phases.setup]
# Esto está correcto, instala Python y una librería extra.
nixPkgs = ["python311", "ffmpeg"]

# Fase 2: Instalar las librerías de Python (CORREGIDO)
[phases.install]
# Le decimos explícitamente que use el 'pip' que viene con 'python3.11'.
# Esta es la corrección más importante.
cmds = ["python3.11 -m pip install --upgrade pip", "python3.11 -m pip install -r requirements.txt"]

# Fase 3: Instalar los navegadores de Playwright
[phases.build]
# Por consistencia, también usamos python3.11 aquí.
cmds = ["python3.11 -m playwright install --with-deps"]

# Fase 4: Comando para iniciar el bot (CORREGIDO)
[start]
# Le decimos explícitamente que ejecute el bot con python3.11.
command = "python3.11 bot.py"
